#!/usr/bin/bash

#Porechop - cut adapters
mkdir fastq_porechoped
SAMPLES=$(ls fastq_joined/*.fastq.gz)
for SAMPLE in $SAMPLES
do
porechop -i $SAMPLE -o fastq_porechoped/"porechoped_$(basename ${SAMPLE})" --discard_middle #-b fastq_porechoped
done

#Quality control
mkdir -p fastQC/porechoped
for file in $(ls fastq_porechoped/*.fastq.gz)
do
    fastqc -t 5 $file -o fastQC/porechoped
done

mkdir -p multiQC
multiqc fastQC/porechoped/*_fastqc.zip -o multiQC --filename porechoped

#Nanofilt - quality filter
mkdir -p fastq_trimmed
SAMPLES=$(ls fastq_porechoped/*.fastq.gz)
for SAMPLE in $SAMPLES
do
gunzip -c $SAMPLE | NanoFilt -q 8 --headcrop 50 | gzip > "fastq_trimmed/trimmed_$(basename ${SAMPLE})"
done

#Quality control
mkdir -p fastQC/trimmed
for file in $(ls fastq_trimmed/*.fastq.gz)
do
    fastqc -t 5 $file -o fastQC/trimmed
done

multiqc fastQC/trimmed/*_fastqc.zip -o multiQC --filename trimmed
