#!/usr/bin/bash

read -p "Run ID: " RUN

mkdir -p fastq_joined
for barcode in $(ls fastq)
do
FASTQ_NUMBER=$(ls fastq/${barcode}/pass | wc -l)
BC=$(echo $barcode | sed 's/^.*barcode//')
echo "${barcode}: ${FASTQ_NUMBER}"
if [ $FASTQ_NUMBER -eq 1 ]; then
	cp fastq/${barcode}/pass/* "fastq_joined/${RUN}_BC${BC}.fastq.gz"
elif [ $FASTQ_NUMBER > 1 ]; then
	cat fastq/${barcode}/pass/*.fastq.gz > "fastq_joined/${RUN}_BC${BC}.fastq.gz"
fi
done

