#!/usr/bin/bash



/home/nanoteam/programs/kraken2/kraken2 --db /home/nanoteam/Desktop/Nano16S-scripts/minikraken2_v2_8GB_201904_UPDATE 
--paired dekont/PK1_2_removed_R1.fastq dekont/PK1_2_removed_R2.fastq --output "kraken/PK1_2.kraken" --report "kraken/PK1_2.kreport2.txt" --use-names

/home/nanoteam/programs/kraken2/kraken2 --db /home/nanoteam/Desktop/Nano16S-scripts/minikraken2_v2_8GB_201904_UPDATE --paired dekont/PK1_2_removed_R1.fastq dekont/PK1_2_removed_R2.fastq --output "kraken/PK1_2.krona.kraken" 


