#!/usr/bin/bash

if [ -z ${FOLDER} ];
then
    read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
else
    echo "Concatenating files from $FOLDER1"
fi

#Concatenate files
DIR=${FOLDER}/output_cat
#mkdir -p $DIR

for file1 in $(ls ${FOLDER}/dekont/*R1.fastq.gz)
   do
    file2=${file1/R1/R2}
    out=$(basename ${file1/R1/joined})
    cat "$file1" "$file2" > ${DIR}/${out} 
   done
