#!/usr/bin/bash

if [ -z ${FOLDER} ];
then
    read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
else
    echo "Quality control run $FOLDER1"
fi

mkdir -p ${FOLDER}/dekont

for file1 in $(ls ${FOLDER}/trimmed/*1_P.fastq.gz)
do
    file2=${file1%%1_P.fastq.gz}"2_P.fastq.gz"
    sample=${file1%%1_P.fastq.gz}
    bowtie2 -x /home/nanoteam/Desktop/Metagenomics-scripts/bowtie2_hg19/hg19 -1 $file1 -2 $file2 --un-conc-gz ${sample}_host_removed > ${sample}_mapped_and_unmapped.sam
mv ${sample}host_removed.1 ${sample}removed_R1.fastq.gz
mv ${sample}host_removed.2 ${sample}removed_R2.fastq.gz
done


