#!/usr/bin/bash

if [ -z ${FOLDER} ];
then
    read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
    read -p "Run quality control on (e.g. rawdata/trimmed/dekont): " DATA
else
    echo "Quality control run $FOLDER1"
fi

DIR=${FOLDER}/fastQC/$DATA

mkdir -p ${DIR}

for file in $(ls ${FOLDER}/Fastq/*_P.fastq.gz)
do
    fastqc -t 10 $file -o ${DIR}
done
