#!/usr/bin/bash

if [ -z ${FOLDER} ];
then
    read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
	read -p "Run quality control on (e.g. rawdata/trimmed/dekont): " DATA
else
    echo "Quality control run $FOLDER1"
fi

INDIR=${FOLDER}/fastQC/$DATA
DIR=${FOLDER}/multiQC

mkdir -p ${DIR}

multiqc ${INDIR}/*_fastqc.zip -o ${DIR} --filename $(basename ${INDIR})
