#!/usr/bin/bash


read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
FOLDER1=$(basename $FOLDER)

#source /home/nanoteam/Desktop/Metagenomics-scripts/fQC
#source /home/nanoteam/Desktop/Metagenomics-scripts/mQC
#source /home/nanoteam/Desktop/Metagenomics-scripts/trim
#source /home/nanoteam/Desktop/Metagenomics-scripts/filthuman_bowtie
#source /home/nanoteam/Desktop/Metagenomics-scripts/align_kraken
source /home/nanoteam/Desktop/Metagenomics-scripts/kronap
#source /home/nanoteam/Desktop/Metagenomics-scripts/bracken
#source /home/nanoteam/Desktop/Metagenomics-scripts/k_biom


