#!/usr/bin/bash

if [ -z ${FOLDER} ];
then
    read -p "Folder (e.g. Metagenomics_zahn): " FOLDER
else
    echo "Quality control run $FOLDER1"
fi

mkdir -p ${FOLDER}/trimmed

for file1 in $(ls ${FOLDER}/Fastq/*1.fastq.gz)
do
    file2=${file1%%1.fastq.gz}"2.fastq.gz"
    sample=$(basename ${file1%%1.fastq.gz})
    ADAPTERS=/home/nanoteam/programs/Trimmomatic-0.39/adapters/NexteraPE-PE.fa:2:30:10
    java -jar /home/nanoteam/programs/Trimmomatic-0.39/trimmomatic-0.39.jar PE -phred33 -trimlog ${FOLDER}/trimmed/${sample}trimlog.txt $file1 $file2 ${FOLDER}/trimmed/${sample}1_P.fastq.gz ${FOLDER}/trimmed/${sample}1_UP.fastq.gz ${FOLDER}/trimmed/${sample}2_P.fastq.gz ${FOLDER}/trimmed/${sample}2_UP.fastq.gz  ILLUMINACLIP:${ADAPTERS} LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36   
done


